# Generated by Django 5.2.6 on 2025-10-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
